### ISSUE TITLE
Connecting to remote SQL Server doesn't work

### ISSUE THREAD

**Issue by rvanoord** [MassTransit/Platform-Quartz#1]
Hi,
It appears that connecting to a remote SQL Server when running docker on Linux doesn't work with these images.

The underlying problem is described in these posts:
https://www.abhith.net/blog/docker-sql-error-on-aspnet-core-alpine/
https://github.com/dotnet/SqlClient/issues/81

I assume adding the following lines to the MassTransit Platform base image will solve the problem:
```
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

**Comment by rvanoord** [comment]
Using the following docker-compose file (which overrides the entrypoint and adds the required environment variable), I was able to use the current image. This confirms that the solutions suggested above should work.

```
version: '3.5'

services:
  mt-quartz-scheduler:
    image: masstransit/quartz:latest
    environment:
     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
     - MT_TRANSPORT=RMQ
     - MT_SCHEDULER=quartz
     - MT_Quartz__ConnectionString=${MT_Quartz__ConnectionString}
     - MT_RMQ__HOST=${MT_RMQ__HOST}
     - MT_RMQ__USER=${MT_RMQ__USER}
     - MT_RMQ__PASS=${MT_RMQ__PASS}
     - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    entrypoint: [sh, -c, "apk add --no-cache icu-libs && dotnet /runtime/MassTransit.Platform.Runtime.dll"]
```
