### ISSUE TITLE
Platform Quartz with Amazon SQS and MySQL

### ISSUE THREAD

**Issue by gsaadeh** [MassTransit/Platform-Quartz#3]
The introduction of the MassTransit Platform is absolutely exciting!

As a first step in the migration towards the platform, I am trying to remove the Quartz scheduler code from the repository and use the Platform image instead.

I've tried using the image directly first, but then realized that it doesn't support MySQL as it's missing a reference to MySql.Data such as:

`<PackageReference Include="MySql.Data" Version="8.0.17" />`

So I copied the code locally to test it and I've added the missing reference.

Before opening a PR, I wanted to give it a try using both MySQL database and the Amazon SQS transport.

Here is what i have in my docker-compose file 

```
  quartz:
    build:
      context: ../src/BuildingBlocks/Platform.Quartz
      dockerfile: ./Dockerfile
    ports:
      - "5002:80"
    environment:
      MT_TRANSPORT: 'SQS'
      MT_SQS__REGION: ''
      MT_Scheduler: 'quartz'
      MT_Quartz__Queue: 'quartz'
      MT_Quartz__ConnectionString: '<the connection string>'
      MT_Quartz__Provider: 'MySql'
    depends_on:
      - mysql
      - localstack
 
```

The container runs successfully and it's able to connect to both Amazon SQS (in localstack) and my other mysql database container.

When I try to schedule a recurring job from the main application container which sends a message to the "quartz" queue, I get the following exception in the quartz container. The same happen for cancelling the scheduling of a message.

```
quartz_1    | [09:46:33 DBG] Created topic MassTransit-Fault--MassTransit_Scheduling-ScheduleRecurringMessage-- arn:aws:sns:us-east-1:000000000000:MassTransit-Fault--MassTransit_Scheduling-ScheduleRecurringMessage--
quartz_1    | [09:46:33 DBG] SEND amazonsqs://docker.localhost/MassTransit-Fault--MassTransit_Scheduling-ScheduleRecurringMessage--?type=topic 00070000-ac12-0242-6bde-08d8b8714703 MassTransit.Fault<MassTransit.Scheduling.ScheduleRecurringMessage>
quartz_1    | [09:46:33 ERR] R-FAULT amazonsqs://docker.localhost/quartz f8860000-436e-784f-b3ee-08d8b87146c0 MassTransit.Scheduling.ScheduleRecurringMessage MassTransit.QuartzIntegration.ScheduleMessageConsumer(00:00:00.0150724)
quartz_1    | System.InvalidOperationException: No constructor for type 'MassTransit.QuartzIntegration.ScheduleMessageConsumer' can be instantiated using services from the service container and default values.
```
Any idea why this happens?

Thanks in advance and great work on the platform again!
